---
- hosts: all
  gather_facts: true
  become: yes


  tasks:
    - name: Add Neovim repository
      apt_repository:
        repo: ppa:neovim-ppa/unstable
    - name: update cache
      ansible.builtin.command: |
        sudo apt-get update

    - name: Install base packages
      become: yes
      ansible.builtin.apt:
        name:
          - git
          - tmux
          - neovim
          - exa
          - ripgrep
          - fzf
          - nodejs
          - stow
          - zsh
        state: present
      # ansible.builtin.command: sudo apt-get install -y neovim zsh tmux stow exa fzf ripgrep

