---
- hosts: all
  gather_facts: false

  vars:
    gotify_server_ip: "{{ server_ip }}"
    gotify_access_token: "{{ access_token }}"
    gotify_message: "{{ hostvars[inventory_hostname].message }}"
    lsb: "{}"

  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
    - name: Send message
      uri:
        url: "http://{{ gotify_server_ip }}/message?token={{ gotify_access_token }}"
        method: POST
        body: "message={{ gotify_message }} lsb: {{ ansible_facts['ansible_lsb'] }}"
        body_format: raw
        status_code: 200
        validate_certs: no
      register: response

    - name: Check response
      debug:
        var: response
