---
- hosts: all
  gather_facts: true

  tasks:
    - name: Clone dotfiles repository
      ansible.builtin.git:
        repo: https://github.com/abroooo/dotfiles.git
        dest: ~/dotfiles
        clone: yes
        update: yes
        version: nvim_lua_config

      # FIXME: this will fail if stow is not installed. fix it!
    - name: Run "stow -S ." inside dotfiles repository
      ansible.builtin.command: stow -S .
      args:
        chdir: ~/dotfiles

    - name: Clone packer.nvim repository
      ansible.builtin.git:
        repo: https://github.com/wbthomason/packer.nvim
        dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
        depth: 1

    - name: Install nvim plugins
      ansible.builtin.shell:
        cmd: "nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'"

    - name: change user shell to zsh 
      become: yes
      user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh

    - name: Install nvim plugins
      ansible.builtin.shell:
        cmd: "curl -sS https://starship.rs/install.sh | sh"

