- name: Execute Docker command
  hosts: host1
  vars:
    immich_directory:  "{{ immich_dir }}"
    lsb: "{}"

  become: yes
  tasks:
    - name: Change directory
      ansible.builtin.shell:
        cmd: cd {{ immich_directory }}

    - name: Pull Docker images
      ansible.builtin.shell:
        cmd: cd {{ immich_directory }} && sudo docker-compose pull

    - name: Stop and remove containers
      ansible.builtin.shell:
        cmd: cd {{ immich_directory }} && sudo docker-compose down

    - name: Start new containers
      ansible.builtin.shell:
        cmd: cd {{ immich_directory }} && sudo docker-compose up --remove-orphans -d

    - name: Remove unused images
      ansible.builtin.shell:
        cmd: sudo docker image prune -f



